[package]
name = "owlmic-media"
description = "Mic, camera and speaker pipelines, smoothers and codecs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
owlmic-hub.workspace = true
owlmic-proto.workspace = true
nnnoiseless.workspace = true
serde_json.workspace = true

[build-dependencies]
cc.workspace = true
