//! Icon geometry, generated by build.rs from the Lucide SVGs in icons/ (24 x 24 box, drawn
//! with a 2 unit stroke at that size).

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Seg {
    Move(f32, f32),
    Line(f32, f32),
    Cubic([f32; 6]),
    Arc {
        radius: (f32, f32),
        rotation: f32,
        large: bool,
        clockwise: bool,
        to: (f32, f32),
    },
    Close,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Shape {
    Path(&'static [Seg]),
    Circle {
        c: (f32, f32),
        r: f32,
    },
    Rect {
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        r: f32,
    },
}

pub type Icon = &'static [Shape];

/// The box Lucide draws in.
pub const BOX: f32 = 24.0;
